### ISSUE TITLE
docker compose error

### ISSUE THREAD

**Issue by mrafieefard** [appujet/lavamusic#593]
I run lavamusic on docker compose and get this error

```lavamusic-lavalink  | 2024-06-30T19:04:20.829Z  INFO 1 --- [           main] lavalink.server.Launcher                 : Starting Launcher v4.0.6 using Java 18.0.2.1 with PID 1 (/opt/Lavalink/Lavalink.jar started by lavalink in /opt/Lavalink)
lavamusic-lavalink  | 2024-06-30T19:04:20.844Z  INFO 1 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
lavamusic-lavalink  | 2024-06-30T19:04:22.419Z  INFO 1 --- [           main] lavalink.server.Launcher                 : Started Launcher in 2.427 seconds (process running for 3.115)
lavamusic-lavalink  | 2024-06-30T19:04:22.469Z  INFO 1 --- [           main] lavalink.server.Launcher                 : 
lavamusic-lavalink  | 
lavamusic-lavalink  |        .   _                  _ _       _    __ _ _
lavamusic-lavalink  |       /\\ | | __ ___   ____ _| (_)_ __ | | __\ \ \ \
lavamusic-lavalink  |      ( ( )| |/ _` \ \ / / _` | | | '_ \| |/ / \ \ \ \
lavamusic-lavalink  |       \\/ | | (_| |\ V / (_| | | | | | |   <   ) ) ) )
lavamusic-lavalink  |        '  |_|\__,_| \_/ \__,_|_|_|_| |_|_|\_\ / / / /
lavamusic-lavalink  |     =========================================/_/_/_/
lavamusic-lavalink  | 
lavamusic-lavalink  |   Version:        4.0.6
lavamusic-lavalink  |   Build time:     06.06.2024 21:02:48 UTC
lavamusic-lavalink  |   Branch          HEAD
lavamusic-lavalink  |   Commit:         8a8ff75
lavamusic-lavalink  |   Commit time:    06.06.2024 20:47:26 UTC
lavamusic-lavalink  |   JVM:            18.0.2.1
lavamusic-lavalink  |   Lavaplayer      2.2.0
lavamusic-lavalink  | 
lavamusic-lavalink  | 2024-06-30T19:04:22.483Z  INFO 1 --- [           main] lavalink.server.Launcher                 : No active profile set, falling back to 1 default profile: "default"
lavamusic-lavalink  | 2024-06-30T19:04:23.287Z  WARN 1 --- [           main] io.undertow.websockets.jsr               : UT026010: Buffer pool was not set on WebSocketDeploymentInfo, the default pool will be used
lavamusic-lavalink  | 2024-06-30T19:04:23.309Z  INFO 1 --- [           main] io.undertow.servlet                      : Initializing Spring embedded WebApplicationContext
lavamusic-lavalink  | 2024-06-30T19:04:23.310Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 820 ms
lavamusic-lavalink  | 2024-06-30T19:04:23.389Z  WARN 1 --- [           main] l.server.config.SentryConfiguration      : Turning off sentry
lavamusic-lavalink  | 2024-06-30T19:04:23.474Z  INFO 1 --- [           main] c.s.d.l.tools.GarbageCollectionMonitor   : GC monitoring enabled, reporting results every 2 minutes.
lavamusic-lavalink  | 2024-06-30T19:04:23.608Z  WARN 1 --- [           main] l.s.config.AudioPlayerConfiguration      : The default Youtube source is now deprecated and won't receive further updates.
lavamusic-lavalink  | You should use the new Youtube source plugin instead.
lavamusic-lavalink  | https://github.com/lavalink-devs/youtube-source#plugin.
lavamusic-lavalink  | To disable this warning, set 'lavalink.server.sources.youtube' to false in your application.yml.
lavamusic-lavalink  | 2024-06-30T19:04:24.157Z  INFO 1 --- [           main] l.server.config.KoeConfiguration         : OS: LINUX, Arch: X86_64
lavamusic-lavalink  | 2024-06-30T19:04:24.157Z  INFO 1 --- [           main] l.server.config.KoeConfiguration         : Enabling JDA-NAS
lavamusic-lavalink  | 2024-06-30T19:04:24.161Z  INFO 1 --- [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: loading with filter null
lavamusic-lavalink  | 2024-06-30T19:04:24.167Z  INFO 1 --- [           main] c.s.l.c.natives.NativeLibraryLoader      : Native library udpqueue: successfully loaded.
lavamusic-lavalink  | 2024-06-30T19:04:24.522Z  INFO 1 --- [           main] io.undertow                              : starting server: Undertow - 2.3.6.Final
lavamusic-lavalink  | 2024-06-30T19:04:24.531Z  INFO 1 --- [           main] org.xnio                                 : XNIO version 3.8.8.Final
lavamusic-lavalink  | 2024-06-30T19:04:24.546Z  INFO 1 --- [           main] org.xnio.nio                             : XNIO NIO Implementation Version 3.8.8.Final
lavamusic-lavalink  | 2024-06-30T19:04:24.652Z  INFO 1 --- [           main] org.jboss.threads                        : JBoss Threads version 3.5.0.Final
lavamusic-lavalink  | 2024-06-30T19:04:24.719Z  INFO 1 --- [           main] o.s.b.w.e.undertow.UndertowWebServer     : Undertow started on port(s) 2333 (http)
lavamusic-lavalink  | 2024-06-30T19:04:24.730Z  INFO 1 --- [           main] lavalink.server.Launcher                 : Started Launcher in 2.304 seconds (process running for 5.426)
lavamusic-lavalink  | 2024-06-30T19:04:24.731Z  INFO 1 --- [           main] lavalink.server.Launcher                 : Lavalink is ready to accept connections.
lavamusic-lavalink  | 2024-06-30T19:04:29.408Z  INFO 1 --- [  XNIO-1 task-2] io.undertow.servlet                      : Initializing Spring DispatcherServlet 'dispatcherServlet'
lavamusic-lavalink  | 2024-06-30T19:04:29.409Z  INFO 1 --- [  XNIO-1 task-2] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
lavamusic-lavalink  | 2024-06-30T19:04:29.410Z  INFO 1 --- [  XNIO-1 task-2] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
lavamusic-lavalink  | 2024-06-30T19:04:29.444Z  WARN 1 --- [  XNIO-1 task-2] l.s.config.RequestAuthorizationFilter    : Authorization failed for 127.0.0.1 on GET /version
lavamusic-lavalink  | 2024-06-30T19:04:29.446Z  INFO 1 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /version
lavamusic           |     
lavamusic           |     █░░ ▄▀█ █░█ ▄▀█ █▀▄▀█ █░█ █▀ █ █▀▀
lavamusic           |     █▄▄ █▀█ ▀▄▀ █▀█ █░▀░█ █▄█ ▄█ █ █▄▄
lavamusic           |                                     
lavamusic           |              .:::.=++=:.:-:             
lavamusic           |             =##############*            
lavamusic           |             *###############.           
lavamusic           |              =++=*####*=++=:            
lavamusic           |                  .*##*:                               
lavamusic           |                .+######*:               
lavamusic           |               =*#########+.             
lavamusic           |             :*############*-            
lavamusic           |            =################*.          
lavamusic           |          :*##################*=         
lavamusic           |        .+######################*:       
lavamusic           |        *#########################.      
lavamusic           |        .::::::::::::::::::::::::.       
lavamusic           | 
lavamusic           | [6/30/2024] [7:04:31 PM] [Lavamusic.js] [Lavamusic] › ℹ  info      Successfully loaded commands!
lavamusic           | [6/30/2024] [7:04:31 PM] [Lavamusic.js] [Lavamusic] › ℹ  info      Successfully loaded events!
lavamusic           | [6/30/2024] [7:04:31 PM] [index.js] [Lavamusic] › ℹ  info      Loaded plugin: AntiCrash Plugin v1.0.0
lavamusic           | [6/30/2024] [7:04:31 PM] [index.js] [Lavamusic] › ℹ  info      Loaded plugin: KeepAlive Plugin v1.0.0
lavamusic           | [6/30/2024] [7:04:31 PM] [index.js] [Lavamusic] › ℹ  info      Loaded plugin: Update Status Plugin v1.0.0
lavamusic           | [6/30/2024] [7:04:32 PM] [Ready.js] [Lavamusic] › ✔  success   Cum#2811 is ready!
lavamusic-lavalink  | 2024-06-30T19:04:32.042Z ERROR 1 --- [  XNIO-1 task-2] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /172.21.0.3:42480
lavamusic-lavalink  | 2024-06-30T19:04:32.043Z  INFO 1 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /v4/websocket
lavamusic           | [6/30/2024] [7:04:32 PM] [NodeError.js] [Lavamusic] › ✖  error     Node Blacky' Error: {}
lavamusic           | [6/30/2024] [7:04:32 PM] [NodeDestroy.js] [Lavamusic] › ✖  error     Node Blacky' destroyed with code 1006 and reason 
lavamusic           | [6/30/2024] [7:04:32 PM] [index.js] [Lavamusic] › ▶  start     [CLIENT] Shard 0 connected to Discord's Gateway.
lavamusic           | [6/30/2024] [7:04:32 PM] [index.js] [Lavamusic] › ▶  start     [CLIENT] 1 shard(s) spawned.
lavamusic           | [6/30/2024] [7:04:32 PM] [Lavamusic.js] [Lavamusic] › ℹ  info      Successfully loaded slash commands!
lavamusic-lavalink  | 2024-06-30T19:04:39.533Z  WARN 1 --- [  XNIO-1 task-2] l.s.config.RequestAuthorizationFilter    : Authorization failed for 127.0.0.1 on GET /version
lavamusic-lavalink  | 2024-06-30T19:04:39.534Z  INFO 1 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /version
lavamusic-lavalink  | 2024-06-30T19:04:49.584Z  WARN 1 --- [  XNIO-1 task-2] l.s.config.RequestAuthorizationFilter    : Authorization failed for 127.0.0.1 on GET /version
lavamusic-lavalink  | 2024-06-30T19:04:49.585Z  INFO 1 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /version
lavamusic-lavalink  | 2024-06-30T19:04:59.653Z  WARN 1 --- [  XNIO-1 task-2] l.s.config.RequestAuthorizationFilter    : Authorization failed for 127.0.0.1 on GET /version
lavamusic-lavalink  | 2024-06-30T19:04:59.653Z  INFO 1 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /version
lavamusic-lavalink  | 2024-06-30T19:05:02.056Z ERROR 1 --- [  XNIO-1 task-2] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /172.21.0.3:35226
lavamusic-lavalink  | 2024-06-30T19:05:02.056Z  INFO 1 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /v4/websocket
lavamusic           | [6/30/2024] [7:05:02 PM] [NodeError.js] [Lavamusic] › ✖  error     Node Blacky' Error: {}
lavamusic           | [6/30/2024] [7:05:02 PM] [NodeDestroy.js] [Lavamusic] › ✖  error     Node Blacky' destroyed with code 1006 and reason 
lavamusic-lavalink  | 2024-06-30T19:05:09.709Z  WARN 1 --- [  XNIO-1 task-2] l.s.config.RequestAuthorizationFilter    : Authorization failed for 127.0.0.1 on GET /version
lavamusic-lavalink  | 2024-06-30T19:05:09.710Z  INFO 1 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /version
lavamusic-lavalink  | 2024-06-30T19:05:19.783Z  WARN 1 --- [  XNIO-1 task-2] l.s.config.RequestAuthorizationFilter    : Authorization failed for 127.0.0.1 on GET /version
lavamusic-lavalink  | 2024-06-30T19:05:19.783Z  INFO 1 --- [  XNIO-1 task-2] l.server.io.RequestLoggingFilter         : GET /version
lavamusic-lavalink  | 2024-06-30T19:05:29.829Z  WARN 1 --- [  XNIO-1 task-2] l.s.config.RequestAuthorizationFilter    : Authorization```

**Comment by pmnlla** [comment]
Having this same issue on Alpine linux without docker. 
```
[7/3/2024] [6:40:46 PM] [Lavamusic.js] [Lavamusic] › ℹ  info      Successfully loaded commands!
[7/3/2024] [6:40:47 PM] [Lavamusic.js] [Lavamusic] › ℹ  info      Successfully loaded events!
[7/3/2024] [6:40:47 PM] [index.js] [Lavamusic] › ℹ  info      Loaded plugin: AntiCrash Plugin v1.0.0
[7/3/2024] [6:40:47 PM] [index.js] [Lavamusic] › ℹ  info      Loaded plugin: KeepAlive Plugin v1.0.0
[7/3/2024] [6:40:47 PM] [index.js] [Lavamusic] › ℹ  info      Loaded plugin: Update Status Plugin v1.0.0
[7/3/2024] [6:40:48 PM] [Ready.js] [Lavamusic] › ✔  success   Mulch#8804 is ready!
[7/3/2024] [6:40:48 PM] [index.js] [Lavamusic] › ▶  start     [CLIENT] Shard 0 connected to Discord's Gateway.
[7/3/2024] [6:40:48 PM] [index.js] [Lavamusic] › ▶  start     [CLIENT] 1 shard(s) spawned.
[7/3/2024] [6:40:48 PM] [NodeError.js] [Lavamusic] › ✖  error     Node Lavamusic Error: {}
[7/3/2024] [6:40:48 PM] [NodeDestroy.js] [Lavamusic] › ✖  error     Node Lavamusic destroyed with code 1006 and reason
[7/3/2024] [6:41:18 PM] [NodeError.js] [Lavamusic] › ✖  error     Node Lavamusic Error: {}
[7/3/2024] [6:41:18 PM] [NodeDestroy.js] [Lavamusic] › ✖  error     Node Lavamusic destroyed with code 1006 and reason
```

**Comment by mrafieefard** [comment]
I found the solution it is the lavamusic docker problem 
I don't know why lavamusic does this but instead of using application.yml as a file and copying it in volume they make it as folder and lavalink can't read config and set a random password so we can't use it
What you need to do just delete application.yml directory and make new one with nano vim or any text editor you use and config your lavalink or you can use public lavalink providers so you don't need config whole lavalink

**Comment by infnibor** [comment]
> I found the solution it is the lavamusic docker problem I don't know why lavamusic does this but instead of using application.yml as a file and copying it in volume they make it as folder and lavalink can't read config and set a random password so we can't use it What you need to do just delete application.yml directory and make new one with nano vim or any text editor you use and config your lavalink or you can use public lavalink providers so you don't need config whole lavalink

Try it now, I have made changes in docker that should fix this error

**Comment by ContinualDissapointment** [comment]
I tried building lava music via docker compose today and I am getting this same error, I'm also noticing an application.yml directory where a file should be. Is it possible this bug came back?
